swagger: "2.0"
info:
  version: "0.0.2"
  title: 18F
# during dev, should point to your local machine
#host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /drug/event/search:
    get:
      x-swagger-router-controller: drugs
      operationId: search
      description: Search field(s)
      parameters:
        - name: field
          in: query
          description: Field to search on.
          required: true
          type: string
        - name: value
          in: query
          description: Value to search on.
          required: true
          type: string
        - name: start
          description: Start Index to return at
          in: query
          required: false
          type: integer
        - name: limit
          in: query
          description: Limit the number of results
          required: false
          type: integer
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Generic"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /drug/event/rangecount:
    get:
      x-swagger-router-controller: drugs
      operationId: rangecount
      description: Returns test fetch of a drugs query count
      parameters:
        - name: start
          in: query
          description: Start day in format YYYYMMDD (ex 20040101)
          required: true
          type: string
        - name: end
          in: query
          description: End day in format YYYYMMDD (ex 20150101)
          required: true
          type: string
        - name: field
          in: query
          description: path of field to count (ex patient.patientsex)
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Generic"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
# complex objects have schema definitions
definitions:
  Generic:
    properties:
      message:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

